Add shaple client
paust-team/shaple-js pull request #1
Opened 2024-01-10 05:05 UTC by 1dennispark

- service GoTrueClient

2024-01-24 12:40 UTC, elon0823 requested changes

2024-01-24 12:40 UTC, elon0823 commented on packages/auth-helpers-shared/src/createClient.ts
> +	return createClient(shapleUrl, {
shapleKey  createClient 쪽으로 같이 넘겨줘야 할 것 같습니다.  createClient 에 shapleKey 를 받는 인터페이스도 빠져있는 것 같습니다.

2024-01-24 16:24 UTC, 1dennispark commented on packages/auth-helpers-shared/src/createClient.ts
> +	return createClient(shapleUrl, {
추가하겠습니다.

2024-01-25 06:32 UTC, elon0823 commented
## Session 이 유지가 안되는 문제
- client component 에서 signInWithPassword 를 호출해서 성공한 뒤, server component 에서 auth.getSession() 을 해보면 session 이 비어있는 상태로 날라오고 있습니다
- local storage 에 `supabase.auth.token`이 저장되고 있습니다

2024-01-25 16:35 UTC, elon0823 approved these changes
SDM 에 적용한 auth 관련 기능들을 supabase 에서 shaple 로 변경해서 적용한 결과 다 정상 작동하는 것을 확인했습니다!

아까 얘기하신 것 처럼 Unit test 가 필요해 보이지만 저도 추후 MSW 등 mocking 해서 하는 방식을 찾아보고 괜찮으면 적용해서 PR 올려보도록 할게요

2024-01-25 16:37 UTC, merged